name: C/C++ CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make libsdl2-dev libsdl2-image-dev libjson-c-dev \
                                libgtest-dev libgmock-dev
        # GoogleTest/GoogleMock installation
        echo "Building GoogleTest..."
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make VERBOSE=1  # Increased verbosity for the build process
        echo "Checking for GoogleTest libraries..."
        ls -l /usr/src/gtest  # List files to verify library presence

        # Verify and copy GoogleTest libraries
        if [ -f libgtest.a ]; then
            sudo cp libgtest.a /usr/lib
            echo "Copied libgtest.a to /usr/lib"
        else
            echo "error: libgtest.a not found"
            exit 1
        fi
        
        if [ -f libgtest_main.a ]; then
            sudo cp libgtest_main.a /usr/lib
            echo "Copied libgtest_main.a to /usr/lib"
        else
            echo "error: libgtest_main.a not found"
            exit 1
        fi

        echo "Building GoogleMock..."
        cd /usr/src/gmock
        sudo cmake CMakeLists.txt
        sudo make VERBOSE=1  # Increased verbosity for the build process
        echo "Checking for GoogleMock libraries..."
        ls -l /usr/src/gmock  # List files to verify library presence

        # Verify and copy GoogleMock libraries
        if [ -f libgmock.a ]; then
            sudo cp libgmock.a /usr/lib
            echo "Copied libgmock.a to /usr/lib"
        else
            echo "error: libgmock.a not found"
            exit 1
        fi
        
        if [ -f libgmock_main.a ]; then
            sudo cp libgmock_main.a /usr/lib
            echo "Copied libgmock_main.a to /usr/lib"
        else
            echo "error: libgmock_main.a not found"
            exit 1
        fi

    - name: Clean and create build directory
      run: |
        rm -rf build/*
        mkdir -p build/tests

    - name: Build Main Application
      run: |
        gcc -I /usr/include/SDL2 \
            -I src \
            src/main.c \
            src/config.c \
            src/components/*.c \
            src/managers/*.c \
            -o build/main.exe \
            -lSDL2 \
            -lSDL2_image \
            -ljson-c \
            -Wall -g

    - name: Build Tests
      run: |
        gcc -I /usr/include/SDL2 \
            src/config.c \
            src/components/*.c \
            src/managers/*.c \
            tests/*.c \
            -lgtest \
            -lgmock \
            -lgtest_main \
            -lgmock_main \
            -o build/tests/tests.exe \
            -Wall -g

    - name: Run Main Application
      run: |
        chmod +x build/main.exe
        ./build/main.exe

    - name: Run Tests
      run: |
        chmod +x build/tests/tests.exe
        ./build/tests/tests.exe
