name: C/C++ CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make libsdl2-dev libsdl2-image-dev libjson-c-dev

    - name: Clean and create build directory
      run: |
        rm -rf build/*
        mkdir -p build/tests

    - name: Build Main Application
      run: |
        gcc -I /usr/include/SDL2 \
            -I src \
            src/main.c \
            src/config.c \
            src/components/*.c \
            src/managers/*.c \
            -o build/main.exe \
            -lSDL2 \
            -lSDL2_image \
            -ljson-c \
            -Wall -g

    - name: Build Tests
      run: |
        gcc -I /usr/include/SDL2 \
            src/config.c \
            src/components/*.c \
            src/managers/*.c \
            tests/*.c \
            -o build/tests/tests.exe \
            -L./lib -lgtest -lgmock -lgtest_main -lgmock_main \
            -Wall -g

    - name: Run Main Application
      run: |
        chmod +x build/main.exe
        ./build/main.exe

    - name: Run Tests
      run: |
        chmod +x build/tests/tests.exe
        ./build/tests/tests.exe
