name: C/C++ CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make cmake libsdl2-dev libsdl2-image-dev libjson-c-dev
        
        # Clone GoogleTest and build it as a shared library
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build && cd build
        cmake .. -DBUILD_SHARED_LIBS=ON
        make
        sudo make install  # Optionally install if needed

    - name: Clean and create build directory
      run: |
        rm -rf build/*
        mkdir -p build/tests

    - name: Build Main Application
      run: |
        gcc -I /usr/include/SDL2 \
            -I /usr/local/include \
            src/main.c \
            src/config.c \
            src/logic.c \
            src/components/*.c \
            src/managers/*.c \
            -o build/main.exe \
            -lSDL2 \
            -lSDL2_image \
            -ljson-c \
            -lgtest \
            -lgtest_main \
            -Wall -g

    - name: Build Tests
      run: |
        gcc -I /usr/include/SDL2 \
            -I /usr/local/include \
            src/config.c \
            src/logic.c \
            src/components/*.c \
            src/managers/*.c \
            tests/*.c \
            -o build/tests/tests.exe \
            -lgtest \
            -lgtest_main \
            -Wall -g

    - name: Run Main Application
      run: |
        chmod +x build/main.exe
        ./build/main.exe

    - name: Run Tests
      run: |
        chmod +x build/tests/tests.exe
        ./build/tests/tests.exe
